version: "3.2"

services:
  nginx:
    restart: always
    image: jwilder/nginx-proxy
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./volumes/config/:/etc/nginx/conf.d"
      - "./volumes/certs:/etc/nginx/certs:ro"
      - "./volumes/vhost.d:/etc/nginx/vhost.d:ro"
      - "./volumes/html:/usr/share/nginx/html"
      - "./volumes/logs:/var/log/nginx"
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"

  letsencrypt:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./volumes/certs:/etc/nginx/certs:rw"
      - "./volumes/vhost.d:/etc/nginx/vhost.d:rw"
      - "./volumes/html:/usr/share/nginx/html"
    environment:
      NGINX_PROXY_CONTAINER: nginx_proxy

  hello:
    restart: always
    image: hello
    build: ./samples/hello
    container_name: hello
    environment:
      VIRTUAL_HOST: hello.thinkimi.com
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: hello.thinkimi.com
      LETSENCRYPT_EMAIL: kimi@thinkimi.com

networks:
  default:
    external:
      name: thinkimi-networks
